providers = ["python"]

[phases.setup]
aptPkgs = ["wkhtmltopdf"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn server:app --workers=2 --threads=2 --bind=0.0.0.0:${PORT:-5000}"


