name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Copy all files to the deployment directory
      - name: Copy files to deployment directory
        run: |
          mkdir -p build
          cp -r static build/
          cp *.html build/
          cp *.js build/
          cp *.css build/
          cp favicon.ico build/ 2>/dev/null || :
          cp intro.mp4 build/ 2>/dev/null || :
          cp -r images build/ 2>/dev/null || :
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true